# Generated by Django 4.2 on 2024-11-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True, null=True, unique=True, verbose_name="ID Телеграмм"
            ),
        ),
    ]
