# Generated by Django 4.2 on 2024-11-24 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=200, verbose_name="место")),
                ("action", models.TextField(verbose_name="действие")),
                ("start_time", models.DateTimeField(verbose_name="время начала")),
                ("end_time", models.DateTimeField(verbose_name="время окончания")),
                ("public", models.BooleanField(verbose_name="публичность")),
                (
                    "is_enjoyable",
                    models.BooleanField(verbose_name="признак приятности"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("ежедневно", "Daily"), ("еженедельно", "Weekly")],
                        default="ежедневно",
                        max_length=12,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "award",
                    models.TextField(
                        blank=True, null=True, verbose_name="вознаграждение"
                    ),
                ),
            ],
            options={
                "verbose_name": "обычная привычка",
                "verbose_name_plural": "обычные привычки",
            },
        ),
        migrations.CreateModel(
            name="RelatedHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=200, verbose_name="место")),
                ("action", models.TextField(verbose_name="действие")),
                ("start_time", models.DateTimeField(verbose_name="время начала")),
                ("end_time", models.DateTimeField(verbose_name="время окончания")),
                ("public", models.BooleanField(verbose_name="публичность")),
                (
                    "is_enjoyable",
                    models.BooleanField(verbose_name="признак приятности"),
                ),
            ],
            options={
                "verbose_name": "желаемая привычка",
                "verbose_name_plural": "желаемые привычки",
            },
        ),
        migrations.AddConstraint(
            model_name="relatedhabit",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="related_habit_start_time_before_end_time",
            ),
        ),
        migrations.AddField(
            model_name="regularhabit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regular_habit",
                to="habits.relatedhabit",
                verbose_name="желаемая привычка",
            ),
        ),
        migrations.AddField(
            model_name="regularhabit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователи",
            ),
        ),
        migrations.AddConstraint(
            model_name="regularhabit",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="regular_habit_start_time_before_end_time",
            ),
        ),
    ]
