# Generated by Django 4.2 on 2024-11-19 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=200, verbose_name="место")),
                ("action", models.TextField(verbose_name="действие")),
                ("start_time", models.DateTimeField(verbose_name="время начала")),
                ("end_time", models.DateTimeField(verbose_name="время окончания")),
                ("public", models.BooleanField(verbose_name="публичность")),
            ],
            options={
                "verbose_name": "желаемая привычка",
                "verbose_name_plural": "желаемые привычки",
            },
        ),
        migrations.CreateModel(
            name="RegularHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=200, verbose_name="место")),
                ("action", models.TextField(verbose_name="действие")),
                ("start_time", models.DateTimeField(verbose_name="время начала")),
                ("end_time", models.DateTimeField(verbose_name="время окончания")),
                ("public", models.BooleanField(verbose_name="публичность")),
                (
                    "frequency",
                    models.CharField(
                        choices=[("ежедневно", "Daily"), ("еженедельно", "Weekly")],
                        default="ежедневно",
                        max_length=12,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(verbose_name="признак приятности"),
                ),
                ("award", models.TextField(verbose_name="вознаграждение")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_habit",
                        to="habits.relatedhabit",
                        verbose_name="желаемая привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователи",
                    ),
                ),
            ],
            options={
                "verbose_name": "обычная привычка",
                "verbose_name_plural": "обычные привычки",
            },
        ),
    ]
