# Generated by Django 4.2 on 2024-11-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="regularhabit",
            constraint=models.CheckConstraint(
                check=models.Q(("start_time__lt", models.F("end_time"))),
                name="start_time_before_end_time",
            ),
        ),
    ]
