# Generated by Django 4.2 on 2024-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedhabit",
            name="frequency",
            field=models.CharField(
                choices=[("ежедневно", "Daily"), ("еженедельно", "Weekly")],
                default="ежедневно",
                max_length=12,
                verbose_name="периодичность",
            ),
        ),
    ]
